services:
  frontend:
    container_name: scorecast-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - scorecast-network
    depends_on:
      - backend
  
  backend:
    container_name: scorecast-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - scorecast-network
    volumes:
      - ./config.toml:/config.toml
      - ./db.json:/db.json
      - output_scorecasts:/output_scorecasts
      - assets:/assets

volumes:
  output_scorecasts:
  assets:

networks:
  scorecast-network:
    driver: bridge